

spring:
  application:
    name: spring-cloud-alibaba-nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: CLOUD
        namespace: 61803b42-a276-4077-b83d-31a85e296630
        service: ${spring.application.name}
        server-addr:
server:
  port: 9001
